# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true
  funlen:
    lines: 70
  nestif:
    min-complexity: 7

linters:
  enable-all: true
  disable:
    - funlen
    - gocognit
    - intrange
    - cyclop
    - gocyclo
    - err113
    - lll
    - gochecknoglobals
    - gomnd
    - wrapcheck
    - paralleltest
    - forbidigo
    - forcetypeassert
    - varnamelen
    - tagliatelle
    - errname
    - ireturn
    - exhaustruct
    - nonamedreturns
    - testableexamples
    - dupword
    - depguard
    - tagalign
    - execinquery
    - mnd
    - testifylint

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - gomnd
        - mnd
        - goconst
        - err113
        - noctx
        - funlen
        - dupl
        - structcheck
        - unused
        - unparam
        - nosnakecase
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - gosec
      path: "example_"

